bachelor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls'))
]

todolist/urls.py
from django.urls import path, include
from . import views
from .views import RegisterView, FeaturesView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', RegisterView.as_view(), name='register'),
    path('features', FeaturesView.as_view(), name='features'),
    path('', views.home, name='home'),
    path('create-list', views.create_list, name='create-list'),
    path('login_redir', views.login_redir, name='login_redir'),
    path('all-lists', views.all_lists, name='all-lists'),
    path('all-lists/<slug:slug>', views.single_list, name='project'),
    path('all-lists/<slug:slug>/create-item', views.create_item, name='create-item'),
    # path('all-lists/<slug:slug>/delete-item', views.delete_item, name='delete-item'),
    path('all-lists/<slug:slug>/<slug:slug_item>', views.edit_item, name='edit-item'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.text import slugify


class ToDoList(models.Model):
    PRIORITY_CHOICES = (
        (1, 'Low'),
        (2, 'Medium'),
        (3, 'High'),
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    made_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    importance = models.IntegerField(choices=PRIORITY_CHOICES, default=2)
    slug = models.SlugField(default='', null=False)
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

class ListItem(models.Model):
    todo = models.CharField(max_length=100, unique=True)
    is_done = models.BooleanField(default=False)
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE, name='todolist')
    slug_item = models.SlugField(default='', null=False)

    def save(self, *args, **kwargs):
        self.slug_item = slugify(self.todo)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.todo
    




# Create your models here.

todolist/forms.py
from .models import ToDoList, ListItem
from django import forms

class ToDoListForm(forms.ModelForm):
    
    class Meta:
        model = ToDoList
        fields = ("title", "importance",)

class ListItemForm(forms.ModelForm):

    class Meta:
        model = ListItem
        fields = ("todo",)

class EditItemForm(forms.ModelForm):

    class Meta:
        model = ListItem
        fields = ("todo", "is_done",)

class DeleteForm(forms.Form):
    delete = forms.CharField()

        

todolist/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from .forms import ToDoListForm, ListItemForm, EditItemForm, DeleteForm
from .models import ToDoList, ListItem
from django.core.exceptions import PermissionDenied

@login_required(login_url="/login")
def home(request):
    lists = ToDoList.objects.filter(author=request.user).order_by("-updated_at")[:3]
    return render(request, 'todolist/home.html',{
        'lists': lists,
    })

@login_required(login_url="/login")
def create_list(request):
    if request.method == 'POST':
        form = ToDoListForm(request.POST)
        if form.is_valid():
            lista = form.save(commit=False)
            lista.author = request.user
            lista.save()
            return redirect(home)
    else:
        form = ToDoListForm()

    return render(request, 'todolist/create_list.html', {
        'form': form
    })
    

class RegisterView(View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'registration/register.html', {
            'form': form
            })

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        return render(request, 'registration/register.html', {'form': form})

class FeaturesView(TemplateView):
    template_name = "features.html"

def login_redir(request):
    return redirect('home')

@login_required(login_url="/login")
def all_lists(request):

    if request.method == 'POST':
        form = DeleteForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            instance = ToDoList.objects.get(title = form.cleaned_data['delete'])
            instance.delete()
            return redirect(all_lists)
    else:
        form = DeleteForm()
    
    low_imp = ToDoList.objects.filter(author=request.user, importance=1).order_by("-updated_at")
    medium_imp = ToDoList.objects.filter(author=request.user, importance=2).order_by("-updated_at")
    high_imp = ToDoList.objects.filter(author=request.user, importance=3).order_by("-updated_at")
    return render(request,'todolist/all_lists.html', {
        "form": form,
        "low_imp": low_imp,
        "medium_imp": medium_imp,
        "high_imp": high_imp
    })
@login_required(login_url="/login")
def single_list(request, slug):

    project = ToDoList.objects.get(slug=slug)

    if project.author != request.user:
        raise PermissionDenied
    
    if request.method == 'POST':
        form = DeleteForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            instance = ListItem.objects.get(todo = form.cleaned_data['delete'])
            instance.delete()
            return redirect(project, slug)
    else:
        form = DeleteForm()
    
    return render(request, 'todolist/single_list.html',{
        "form": form,
        "project": project
    })

@login_required(login_url="/login")
def single_item(request,slug):
    project = ToDoList.objects.filter(author=request.user, importance=1).order_by("-updated_at")
    if project.author != request.user:
        raise PermissionDenied
    return render(request, 'todolist/single_list.html',{
        "project": project
    })

@login_required(login_url="/login")
def create_item(request, slug):
    project = ToDoList.objects.get(slug=slug)
    if request.method == 'POST':
        form = ListItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.todolist = project
            item.save()
            return redirect(single_list, slug)
    else:
        form = ListItemForm()

    return render(request, 'todolist/create_list.html', {
        'form': form
    })

@login_required(login_url="/login")
def edit_item(request, slug, slug_item):
    item = ListItem.objects.get(slug_item=slug_item)
    if request.method == 'POST':
        form = EditItemForm(request.POST)
        if form.is_valid():
            item.todo = form.cleaned_data['todo']
            item.is_done = form.cleaned_data['is_done']
            item.save()
            return redirect(single_list, slug)
    else:
        form = EditItemForm()
    return render(request, 'todolist/edit_item.html', {
        'form': form
    })

# @login_required(login_url="/login")
# def delete_item(request, slug):
#     project = ToDoList.objects.get(slug=slug)
#     if request.method == 'POST':
#         form = ListItemForm(request.POST)
#         if form.is_valid():
#             item = form.save(commit=False)
#             item.todolist = project
#             item.save()
#             return redirect(single_list, slug)
#     else:
#         form = ListItemForm()

#     return render(request, 'todolist/delete_item.html', {
#         'form': form
#     })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    {% block css_files %}
    
    {% endblock  %}
    <title>{% block title %}{% endblock  %}</title>
</head>
<body>
    {% include 'includes/navbar.html' %}
    {% block content %}
    
    {% endblock  %}
    {% include 'includes/footer.html' %}
</body>
</html>

templates/includes/footer.html
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'includes/footer.css' %}">
{% endblock  %}


<footer>
    <p>&copy; 2023 ToDoList. All rights reserved.</p>
    <p>Contact: nieciowy@gmail.com</p>
</footer>

templates/includes/navbar.html
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'includes/navbar.css' %}">
{% endblock  %}

<ul class="navbar">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'features' %}">Features</a></li>
    {% if user.is_authenticated %}
    <li class="right"><span>Logged in as {{user.username}} |</span></li>
    <li class="right register"><a href="{% url 'logout' %}">Logout</a></li>
    {% else %}
    <li class="right"><a href="{% url 'login' %}">Login</a></li>
    <li class="right register"><a href="{% url 'register' %}">Register</a></li>
    {% endif %}
</ul>

todolist/templates/todolist/all_lists.html
{% extends 'base.html' %}

{% block content %}
<center>
    <h3>ALL YOUR PROJECTS:</h3>
    <div>
        <h2>High importance</h2>
        {% for list in high_imp %}
            {% include 'todolist/project_small.html' %}
        {% endfor %}
        <h2>Medium importance</h2>
        {% for list in medium_imp %}
            {% include 'todolist/project_small.html' %}
        {% endfor %}
        <h2>Low importance</h2>
        {% for list in low_imp %}
            {% include 'todolist/project_small.html' %}
        {% endfor %}
    </div>
    <h3>WRITE NAME OF THE ITEM YOU WANT TO DELETE AND CLICK DELETE</h3>
        <form method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="DELETE">
            <input type="hidden" name="next" value="{{ next }}">
        </form>
</center>
{% endblock  %}

todolist/templates/todolist/create_item.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Create new item{% endblock  %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Done">
    <input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock  %}

todolist/templates/todolist/create_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Create new list{% endblock  %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Done">
    <input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock  %}

todolist/templates/todolist/delete_item.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<center>
    <h1>Title: {{project.title}}</h1>
    <form>
        {% csrf_token %}
        {% if project.listitem_set.all == null %}
        <h4>No List Elelements To Delete</h4>
        {% else %}
        {% for element in project.listitem_set.all %}
            {% if element.is_done %}
            <h5><s>{{element.todo}}</s></h5>
            {% else %}
            <h5>{{element.todo}}</h5>
            {% endif %}
        {% endfor %}
        <h4>
            Type In element to delete
        </h4>
        {{form|crispy}}
        {% endif %}
        <center>
        </center>
    </form>
</center>

{% endblock  %}

todolist/templates/todolist/edit_item.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Create new list{% endblock  %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Done">
    <input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock  %}

todolist/templates/todolist/features.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% include 'includes/navbar.html' %}

{% endblock  %}

todolist/templates/todolist/home.html
{% extends 'base.html' %}

{% load static %}

{% block css_files %}
    <link rel="stylesheet" href="{% static 'todolist/home.css' %}">
{% endblock  %}

{% block content %}
<center>
    <h3><a href="{% url 'create-list' %}">ADD NEW PROJECT</a></h3>
</center>

<center>
    <h3>YOUR LATEST PROJECTS:</h3>
    <div>
        {% for list in lists %}
            {% include 'todolist/project_small.html' %}
        {% endfor %}
    </div>
</center>

<center>
    <h3><a href="{% url 'all-lists' %}">ALL YOUR PROJECTS</a></h3>
</center>
    

{% endblock  %}

todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'todolist/login.css' %}">
{% endblock  %}

{% block content %}

{% include 'includes/navbar.html' %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
    <h3>Give data to login</h3>
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
            </tr>
        </table>
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
<input type="submit" value="Login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
{% comment %} <p><a href="{% url 'password_reset' %}">Lost password?</a></p> {% endcomment %}

{% endblock %}

todolist/templates/todolist/project_small.html
<h4><a href="{% url 'project' list.slug%}">Title: {{list.title}}</a></h4>

todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'todolist/login.css' %}">
{% endblock  %}

{% block content %}

{% include 'includes/navbar.html' %}

{% if next %}
    {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
    {% else %}
        <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'register' %}">
    <h3>Give data to register</h3>
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td></td>
            <td><p class="error-message">{{ form.username.errors}}</p></td>
        </tr>
        <tr>
            <td>{{ form.password1.label_tag }}</td>
            <td>{{ form.password1 }}</td>
        </tr>
        <tr>
            <td></td>
            <td><p class="error-message">{{ form.password1.errors}}</p></td>
        </tr>
        <tr>
            <td>{{ form.password2.label_tag }}</td>
            <td>{{ form.password2 }}</td>
            </tr>
            <tr>
                <td></td>
                <td><p class="error-message">{{ form.password2.errors}}</p></td>
            </tr>
        </tr>
    </table>
    <input type="submit" value="Register">
    <input type="hidden" name="next" value="{{ next }}">
</form>
{% endblock  %}

todolist/templates/todolist/single_list.html
{% extends 'base.html' %}

{% block content %}

<center>
    <h1>Title: {{project.title}}</h1>
        {% csrf_token %}
        {% if project.listitem_set.all == null %}
        <h4>No List Elelements</h4>
        {% else %}
        {% for element in project.listitem_set.all %}
            {% if element.is_done %}
            <h5><a href="{% url 'edit-item' project.slug element.slug_item %}"><s>{{element.todo}}</s></a></h5>
            {% else %}
            <h5><a href="{% url 'edit-item' project.slug element.slug_item %}">{{element.todo}}</a></h5>
            {% endif %}
            
        {% endfor %}
        {% endif %}
        <center>
            <h3><a href="{% url 'create-item' project.slug %}">CREATE NEW ITEM</a></h3>
            <h3>WRITE NAME OF THE ITEM YOU WANT TO DELETE AND CLICK DELETE</a></h3>
            <form method="post">
                {% csrf_token %}
                {{form}}
                <input type="submit" value="DELETE">
                <input type="hidden" name="next" value="{{ next }}">
            </form>
        </center>
</center>

{% endblock  %}